server:
  port: 8800
spring:
  application:
    name: mall-front
# Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      registry-fetch-interval-seconds: 5
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true