server:
  port: 7700
spring:
  application:
    name: mall-item
# Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      registry-fetch-interval-seconds: 5
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
# knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  # 如果为true则开启生产环境屏蔽
  production: false
  basic:
    enable: true
    username: mall-item
    password: mall-item@/147